"""Pydantic schemas for YorkPulse API."""

from app.schemas.auth import (
    IDUploadRequest,
    IDUploadResponse,
    IDVerificationRequest,
    IDVerificationResponse,
    LoginRequest,
    NameVerificationRequest,
    NameVerificationResponse,
    ProfileUpdateRequest,
    RefreshTokenRequest,
    SignupRequest,
    SignupResponse,
    TokenResponse,
    UserResponse,
    VerifyEmailRequest,
)
from app.schemas.buddy import (
    BuddyRequestCreate,
    BuddyRequestFilters,
    BuddyRequestListResponse,
    BuddyRequestResponse,
    BuddyRequestUpdate,
    JoinRequestCreate,
    ParticipantAction,
    ParticipantListResponse,
    ParticipantResponse,
)
from app.schemas.marketplace import (
    ImageUploadRequest,
    ImageUploadResponse,
    ListingCreate,
    ListingFilters,
    ListingListResponse,
    ListingResponse,
    ListingUpdate,
)
from app.schemas.messaging import (
    ConversationAction,
    ConversationCreate,
    ConversationListResponse,
    ConversationResponse,
    MarkReadRequest,
    MessageCreate,
    MessageListResponse,
    MessageResponse,
)
from app.schemas.review import (
    ReviewCreate,
    ReviewListResponse,
    ReviewResponse,
    UserRatingSummary,
)
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserInDB,
    UserMinimal,
    UserPublic,
)
from app.schemas.vault import (
    FlagRequest,
    VaultCommentCreate,
    VaultCommentListResponse,
    VaultCommentResponse,
    VaultCommentUpdate,
    VaultPostCreate,
    VaultPostListResponse,
    VaultPostResponse,
    VaultPostUpdate,
)
from app.schemas.gig import (
    GigCreate,
    GigUpdate,
    GigResponse,
    GigListResponse,
    GigResponseCreate,
    GigResponseItem,
    GigResponsesListResponse,
    GigResponseActionResult,
    GigTransactionResponse,
    GigTransactionListResponse,
    GigCompleteResult,
    GigRatingCreate,
    GigRatingResponse,
    GigRatingListResponse,
    GigProfileResponse,
    MyGigsResponse,
    GigFilters,
    GigUserInfo,
    GigUserMinimal,
)

__all__ = [
    # Auth
    "SignupRequest",
    "SignupResponse",
    "VerifyEmailRequest",
    "LoginRequest",
    "TokenResponse",
    "RefreshTokenRequest",
    "NameVerificationRequest",
    "NameVerificationResponse",
    "IDUploadRequest",
    "IDUploadResponse",
    "IDVerificationRequest",
    "IDVerificationResponse",
    "UserResponse",
    "ProfileUpdateRequest",
    # User
    "UserBase",
    "UserCreate",
    "UserInDB",
    "UserPublic",
    "UserMinimal",
    # Vault
    "VaultPostCreate",
    "VaultPostUpdate",
    "VaultPostResponse",
    "VaultPostListResponse",
    "VaultCommentCreate",
    "VaultCommentUpdate",
    "VaultCommentResponse",
    "VaultCommentListResponse",
    "FlagRequest",
    # Marketplace
    "ListingCreate",
    "ListingUpdate",
    "ListingResponse",
    "ListingListResponse",
    "ListingFilters",
    "ImageUploadRequest",
    "ImageUploadResponse",
    # Buddy
    "BuddyRequestCreate",
    "BuddyRequestUpdate",
    "BuddyRequestResponse",
    "BuddyRequestListResponse",
    "BuddyRequestFilters",
    "JoinRequestCreate",
    "ParticipantResponse",
    "ParticipantListResponse",
    "ParticipantAction",
    # Messaging
    "ConversationCreate",
    "ConversationResponse",
    "ConversationListResponse",
    "ConversationAction",
    "MessageCreate",
    "MessageResponse",
    "MessageListResponse",
    "MarkReadRequest",
    # Review
    "ReviewCreate",
    "ReviewResponse",
    "ReviewListResponse",
    "UserRatingSummary",
    # Gig
    "GigCreate",
    "GigUpdate",
    "GigResponse",
    "GigListResponse",
    "GigResponseCreate",
    "GigResponseItem",
    "GigResponsesListResponse",
    "GigResponseActionResult",
    "GigTransactionResponse",
    "GigTransactionListResponse",
    "GigCompleteResult",
    "GigRatingCreate",
    "GigRatingResponse",
    "GigRatingListResponse",
    "GigProfileResponse",
    "MyGigsResponse",
    "GigFilters",
    "GigUserInfo",
    "GigUserMinimal",
]
